<Project Sdk="Microsoft.NET.Sdk">

  <!-- Project Settings -->
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Firebelley.GodotUtilities.SourceGenerators</AssemblyName>
    <RootNamespace>GodotUtilities.SourceGenerators</RootNamespace>
  </PropertyGroup>

  <!-- Package Settings -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>Firebelley</Authors>
    <Description>
      Source generators to accompany Firebelley.GodotUtilities.
    </Description>
    <RepositoryUrl>https://github.com/firebelley/GodotUtilities</RepositoryUrl>
    <PackageProjectUrl>https://github.com/firebelley/GodotUtilities</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>GodotUtilities</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>6.0.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" Link="Package\docs\README.md" />
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers\dotnet\cs" Link="Package\analyzers\dotnet\cs\$(AssemblyName).dll" />
  </ItemGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="IsExternalInit" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.5.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
